default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: appdevelopment
  username: postgres
  password: postgres
  host: 127.0.0.1

test:
  <<: *default
  database: app_test
  username: postgres
  password: postgres
  host: 127.0.0.1
