default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432


development:
  <<: *default
  database: thinknetka_development
  username: username
  password: password
  host: 127.0.0.1


test:
  <<: *default
  database: thinknetka_test
  username: username
  password: password
  host: 127.0.0.1
   